name: Bug Report
description: Report errors or unexpected results.
labels: ["bug"]
assignees:
  - gpauloski
body:
  - type: textarea
    id: install
    attributes:
      label: How did you install the benchmarks?
      description: >
        E.g., install via pip, install from source, etc. **Note:** this will
        be rendered as console text automatically.
      placeholder: |
        $ pip install foobar
        Collecting foobar
        ...
        Successfully installed foobar...
      render: console
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: What version are you using?
      description: >
        Commit ID or Git tag.
      placeholder: v1.2.3
    validations:
      required: true

  - type: textarea
    id: freeform
    attributes:
      label: Describe the problem.
      description: >
        Please provide sample code and directions for reproducing
        your problem and what you expected to happen.
    validations:
      required: true
